config/routes.rb
Rails.application.routes.draw do
  root    'static_pages#home'
  get     '/login',               to: 'sessions#create'
  resources :teachers,            only: [:index, :new, :create] do
    member do
      get :vouted_teachers, 
          :teacher_voters, 
          :voted_courses
    end
  end
  resources :courses,             only: [:new, :create] do
    member do
      get :course_voters
    end
  end
  resources :course_registries,   only: [:index, :new, :create]
  resources :teacher_votes,       only: [:create]
  resources :course_votes,        only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :course_registry
  has_many :course_votes
  has_many :course_voters, through: :course_votes, source: :teacher
  validates :title, presence: true, length: { maximum: 300 }, uniqueness: true
end

app/models/course_registry.rb
class CourseRegistry < ApplicationRecord
  belongs_to :teacher
  belongs_to :course
  validates :teacher_id, presence: true
  validates :course_id, presence: true
  validates_uniqueness_of :teacher_id, :scope => :course_id
end

app/models/course_vote.rb
class CourseVote < ApplicationRecord
  belongs_to :teacher
  belongs_to :course
  validates :teacher_id, presence: true
  validates :course_id, presence: true
  validates_uniqueness_of :teacher_id, :scope => :course_id
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :course_registry
  has_many :active_tearcher_votes, class_name: "TeacherVote",
                                   foreign_key: "voter_teacher_id"
  has_many :passive_tearcher_votes, class_name:  "TeacherVote",
                                    foreign_key: "voted_teacher_id"
  has_many :vouted_teachers, through: :active_tearcher_votes, source: :voted_teacher
  has_many :teacher_voters, through: :passive_tearcher_votes, source: :voter_teacher
  has_many :course_votes
  has_many :voted_courses, through: :course_votes, source: :course
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 100 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
                    
  def vote_theacher(other_teacher)
    vouted_teachers << other_teacher
  end

  def voted_teacher?(other_teacher)
    vouted_teachers.include?(other_teacher)
  end
                    
  def vote_course(course)
    voted_courses << course
  end

  def voted_course?(course)
    voted_courses.include?(course)
  end
  
end

app/models/teacher_vote.rb
class TeacherVote < ApplicationRecord
  belongs_to :voter_teacher, class_name: "Teacher"
  belongs_to :voted_teacher, class_name: "Teacher"
  validates :voter_teacher_id, presence: true
  validates :voted_teacher_id, presence: true
  validates_uniqueness_of :voter_teacher_id, :scope => :voted_teacher_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/course_registries_controller.rb
class CourseRegistriesController < ApplicationController
  
  def index
    @course_registries = CourseRegistry.all
  end
  
  def new
    @courses = Course.all
    @course_registry = CourseRegistry.new
  end
  
  def create
    @course_registry = CourseRegistry.new(teacher_id: params[:teacher_id], course_id: params[:course_id])
    if @course_registry.save
      flash[:success] = "Course Registry created successfully!"
      redirect_to course_registries_url
    else
      flash[:warning] = "Course previously registered"
      redirect_to new_course_registry_url
    end
  end
  
  private
  
    def course_registry_params
      params.require(:course_registry).permit(:teacher_id, :course_id)
    end
  
end

app/controllers/course_votes_controller.rb
class CourseVotesController < ApplicationController

  def create
    voted_course = Course.find(params[:course_id])
    begin
      current_teacher.vote_course(voted_course)
      flash[:success] = "Course voted successfully!"
    rescue 
      flash[:warning] = "Course previously voted"
    end
    redirect_to course_registries_url
  end
  
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  
  def new
    @course = Course.new
  end
  
  def create
    @course = Course.new(course_params)
    if @course.save
      flash[:success] = "Course created successfully!"
      redirect_to new_course_registry_url
    else
      render 'new'
    end
  end
  
  private
  
    def course_params
      params.require(:course).permit(:title)
    end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    teacher = Teacher.find_by(id: params[:user_id])
    if teacher
      log_in teacher
      redirect_to course_registries_url
    else
      flash.now[:danger] = 'Invalid Teacher'
      redirect_to teachers_url
    end
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/teacher_votes_controller.rb
class TeacherVotesController < ApplicationController

  def create
    voted_teacher = Teacher.find(params[:voted_teacher_id])
    begin
      current_teacher.vote_theacher(voted_teacher)
      flash[:success] = "Theacher voted successfully!"
    rescue 
      flash[:warning] = "Teacher previously voted"
    end
    redirect_to course_registries_url
  end
  
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  
  def index
    @teachers = Teacher.all
  end
  
  def new
    @teacher = Teacher.new
  end
  
  def create
    @teacher = Teacher.new(teacher_params)
    if @teacher.save
      flash[:success] = "Teacher created successfully!"
      redirect_to teachers_url
    else
      render 'new'
    end
  end
  
  private
  
    def teacher_params
      params.require(:teacher).permit(:name, :email)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_registries_helper.rb
module CourseRegistriesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(teacher)
    session[:teacher_id] = teacher.id
  end
  
  def current_teacher
    if session[:teacher_id]
      @current_teacher ||= Teacher.find_by(id: session[:teacher_id])
    end
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/course_registries/index.html.erb
<% provide(:title, 'Course Registration List') %>
<% @teacher ||= current_teacher %>
<div class="jumbotron">
  <h2><%= @teacher.name %></h2>
  <h2>Course Registration List</h2>
  <table class="table">
    <thead>
      <tr>
        <th scope="col" colspan="2">Teacher</th>
        <th scope="col" colspan="2">Course</th>
      </tr>
    </thead>
    <tbody>
    <% @course_registries.each do |course_registry| %>
     <tr>
        <td style="vertical-align: middle">
          <%= course_registry.teacher.name %> <strong><em>(<%= course_registry.teacher.teacher_voters.count %> votes)</em></strong>
        </td>
        <td>
          <% if @teacher.voted_teacher?(course_registry.teacher) %>
            <button type="button" disabled="true" style="width:130px; height:34px">Teacher Voted</button>
          <% else %>
            <%= form_with(model: course_registry.teacher.active_tearcher_votes.build, local: true) do |f| %>
              <div><%= hidden_field_tag :voted_teacher_id, course_registry.teacher.id %></div>
              <%= f.submit "Vote Teacher", class: "btn btn-primary", disable: true, style: "width:130px" %>
            <% end %>
          <% end %>
        </td>
        <td style="vertical-align: middle">
          <%= course_registry.course.title %> <strong><em>(<%= course_registry.course.course_voters.count %> votes)</em></strong>
        </td>
        <td>
          <% if @teacher.voted_course?(course_registry.course) %>
            <button type="button" disabled="true" style="width:130px; height:34px">Course Voted</button>
          <% else %>
            <%= form_with(model: course_registry.teacher.course_votes.build, local: true) do |f| %>
              <div><%= hidden_field_tag :course_id, course_registry.course.id %></div>
              <%= f.submit "Vote Course", class: "btn btn-primary", disable: true, style: "width:130px" %>
            <% end %>
          <% end %>
        </td>
     </tr>
    <% end %>
    </tbody>
  </table>
  <div style="text-align:center">
    <%= link_to "Register New Course", new_course_registry_path, class: "btn center btn-lg btn-primary", style: "margin-top:5px" %>
  </div>
</div>

app/views/course_registries/new.html.erb
<% provide(:title, 'Course Registration') %>
<% @teacher ||= current_teacher %>
<div class="jumbotron">
  <h2><%= @teacher.name %></h2>
  <h2>Course List</h2>
  <table class="table">
    <thead>
      <tr>
        <th scope="col" colspan="2">Course</th>
      </tr>
    </thead>
    <tbody>
      <% @courses.each do |course| %>
        <tr>
          <td style="vertical-align: middle">
            <%= course.title %>
          </td>
          <td>
            <%= form_with(model: @course_registry, remote: true) do |f| %>
              <div><%= hidden_field_tag :teacher_id, @teacher.id %></div>
              <div><%= hidden_field_tag :course_id, course.id %></div>
              <%= f.submit "Register Course", class: "btn btn-primary float-right", style: "width:130px; margin-right:10px" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div style="text-align:center">
    <%= link_to "Create New Course", new_course_path, class: "btn btn-lg btn-primary", style: "margin-top:5px" %>
  </div>
</div>

app/views/courses/new.html.erb
<% provide(:title, 'New Course') %>
<div class="row">
  <h1>New Course</h1>
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @course, local: true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
      <%= f.submit "Create Course", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Teacher Management APP by Carlos Benito
  </small>
  <nav>
    <ul>
      <li><a href="https://github.com/CarlosBenito85/teacher_management_app">Repository</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Teacher Management APP", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Teacher Login Simulation", teachers_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Teacher Management APP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>Teacher Management APP</h1>
  <h2>Welcome to the Home page</h1>
  <%= link_to "START", teachers_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/teachers/index.html.erb
<% provide(:title, 'Teachers List') %>
<div class="jumbotron">
  <h2>
    Page to simulate the teacher login in the Teacher Managamente APP.</br>
    Click on the teacher name to continue.
  </h2>
  <ul class="item_list">
    <% @teachers.each do |teacher| %>
     <li>
        <strong><%= link_to teacher.name, login_path(:user_id => teacher.id) %></strong> - <%= teacher.email %>
     </li>
    <% end %>
  </ul>
  <div style="text-align:center">
    <%= link_to "Create New Teacher", new_teacher_path, class: "btn btn-lg btn-primary", style: "margin-top:20px" %>
  </div>
</div>

app/views/teachers/new.html.erb
<% provide(:title, 'New Teacher') %>
<div class="row">
  <h1>New Teacher</h1>
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @teacher, local: true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      <%= f.submit "Create Teacher", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>